# Generated by Django 3.1.4 on 2020-12-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imgagem_post',
            new_name='imagem_post',
        ),
    ]
