# Generated by Django 3.1.4 on 2020-12-23 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20201223_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='titulo_pots',
            new_name='titulo_post',
        ),
    ]
