# Generated by Django 3.1.4 on 2020-12-27 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20201223_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='excerto_post',
            new_name='resumo_post',
        ),
    ]
