# Generated by Django 3.1.4 on 2020-12-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='publicado_comentario',
            field=models.BooleanField(default=False),
        ),
    ]
