# Generated by Django 3.1.4 on 2020-12-27 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_comentarios_publicado_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarios',
            options={'verbose_name_plural': 'comentários'},
        ),
    ]
