# Generated by Django 3.1.4 on 2020-12-27 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0003_auto_20201227_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='email_comentario',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='comentarios',
            old_name='nome_comentario',
            new_name='nome',
        ),
    ]
