# Generated by Django 3.1.4 on 2021-01-18 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0006_respostas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Respostas',
        ),
    ]
