# Generated by Django 3.1.4 on 2021-02-11 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0008_auto_20210126_0650'),
        ('notificaçoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='comentario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_resp', to='comentarios.resposta'),
        ),
    ]
