# Generated by Django 3.1.4 on 2021-02-12 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaçoes', '0003_auto_20210211_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='enviar',
            new_name='user_from',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='usuario',
            new_name='user_to',
        ),
    ]
