# Generated by Django 3.1.4 on 2021-02-23 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20210124_0247'),
        ('notificaçoes', '0004_auto_20210212_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='new_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_post', to='post.post'),
        ),
    ]
