# Generated by Django 3.1.4 on 2021-02-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaçoes', '0005_notification_new_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='new_post',
            new_name='post',
        ),
    ]
