# Generated by Django 3.1.4 on 2021-02-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaçoes', '0006_auto_20210223_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'Posts'), (2, 'Respostas')]),
        ),
    ]
