# Generated by Django 3.1.4 on 2021-02-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('email_enviados', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Emails cadastrados',
            },
        ),
    ]
